---
title: "Sequencing depth analysis"
author: "Laia Domingo Costa"
format: html
editor: visual
---

## Load libraries

```{r}
library(ggplot2)
```

## Load data

```{r}
concat_track_table = read.csv("DATA/NHP_7jun2024_concatenated_tracktable.tsv", sep = "\t")
presence_absence_genus_table = read.csv("DATA/nhp_13jun2024_euk_presence_absence_genus_table_def.tsv", sep = "\t")
```

## Preprocessing and summaries

```{r}
presence_absence_genus_table$Sum = rowSums(presence_absence_genus_table[, -1])

# Summary of taxID counts
summary(presence_absence_genus_table$Sum)

# Select the interest columns
track_table_fi = concat_track_table[, c(1, 4)]
conteos_fi = presence_absence_genus_table[, c("Sample", "Sum")]

# Summary of the number of reads
summary(concat_track_table$bowtie)

# Merge the final track_table with the Bowtie reading count together with the total sum of taxa found per sample
merge = merge(track_table_fi, conteos_fi, by = "Sample")
```

## Dot plot

```{r}
# Create the dot plot with ggplot2
ggplot(merge, aes(x = log10(merge$bowtie), y = merge$Sum)) +
  geom_point(color = "#F87666", size = 3) +
  labs(x = "Number of reads (log10)", y = "TaxID counts") +
  geom_vline(xintercept = log10(1500000), color = "#598392", size=1.5) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(limits=c(6,9.5), breaks=seq(6, 9.5, 0.5))

ggsave("Graficas/Sequencing_depth.png")
```
